<br>

# FDBS

_Script_ para obter dados usando LXML.

Quero simplificar!

<br>

Michel Metran\
Data: 02.11.2025\
Atualizado em: 23.09.2026

In [20]:
import time
from pathlib import Path

import pandas as pd

from pyFBDS.logger import FBDSLogger
from pyFBDS.lxml import FBDS

# from pyFBDS.lxml import  download

<br>

---

## Pastas

In [21]:
project_path = Path(".").absolute().parents[2]

# Diretório de saída
data_path = project_path / "data"

logs_path = data_path / "log"
logs_path.mkdir(parents=True, exist_ok=True)

output_path = data_path / "output"
output_path.mkdir(parents=True, exist_ok=True)
output_path

WindowsPath('d:/Codes/GitHub/Org - Open Geodata/pyFBDS/data/output')

<br>

---

## FBDS

Instancia a classe

In [22]:
# Instancia Logger
logger = FBDSLogger(
    log_dir=logs_path,
    new_session=True,
)

# Instancia FBDS
fbds = FBDS(
    temp_path=output_path,
    output_path=output_path,
    logger=logger,
)

<br>

---

### States

Lista estados

In [23]:
estados = fbds.get_states()
estados

2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/

[{'url': 'https://geo.fbds.org.br/AC/',
  'type': 'folder',
  'name': 'AC',
  'date': '2022-10-10 14:32',
  'size': '1339563 KB'},
 {'url': 'https://geo.fbds.org.br/AL/',
  'type': 'folder',
  'name': 'AL',
  'date': '2022-04-30 01:22',
  'size': '1789015 KB'},
 {'url': 'https://geo.fbds.org.br/AM/',
  'type': 'folder',
  'name': 'AM',
  'date': '2022-10-10 14:42',
  'size': '12583137 KB'},
 {'url': 'https://geo.fbds.org.br/AP/',
  'type': 'folder',
  'name': 'AP',
  'date': '2022-10-10 14:56',
  'size': '1557080 KB'},
 {'url': 'https://geo.fbds.org.br/BA/',
  'type': 'folder',
  'name': 'BA',
  'date': '2022-12-08 20:19',
  'size': '15946035 KB'},
 {'url': 'https://geo.fbds.org.br/CE/',
  'type': 'folder',
  'name': 'CE',
  'date': '2021-08-05 21:31',
  'size': '6915954 KB'},
 {'url': 'https://geo.fbds.org.br/DF/',
  'type': 'folder',
  'name': 'DF',
  'date': '2019-07-29 15:39',
  'size': '182179 KB'},
 {'url': 'https://geo.fbds.org.br/ES/',
  'type': 'folder',
  'name': 'ES',
  'date': '2019-07-29 15:38',
  'size': '2508187 KB'},
 {'url': 'https://geo.fbds.org.br/GO/',
  'type': 'folder',
  'name': 'GO',
  'date': '2019-07-29 15:39',
  'size': '15695581 KB'},
 {'url': 'https://geo.fbds.org.br/MA/',
  'type': 'folder',
  'name': 'MA',
  'date': '2022-12-08 21:16',
  'size': '10603194 KB'},
 {'url': 'https://geo.fbds.org.br/MG/',
  'type': 'folder',
  'name': 'MG',
  'date': '2024-08-15 18:21',
  'size': '34075793 KB'},
 {'url': 'https://geo.fbds.org.br/MS/',
  'type': 'folder',
  'name': 'MS',
  'date': '2019-07-29 15:39',
  'size': '10955512 KB'},
 {'url': 'https://geo.fbds.org.br/MT/',
  'type': 'folder',
  'name': 'MT',
  'date': '2024-08-15 19:39',
  'size': '16348898 KB'},
 {'url': 'https://geo.fbds.org.br/PA/',
  'type': 'folder',
  'name': 'PA',
  'date': '2025-11-19 14:51',
  'size': '19830900 KB'},
 {'url': 'https://geo.fbds.org.br/PB/',
  'type': 'folder',
  'name': 'PB',
  'date': '2021-10-15 02:55',
  'size': '3844515 KB'},
 {'url': 'https://geo.fbds.org.br/PE/',
  'type': 'folder',
  'name': 'PE',
  'date': '2021-08-06 05:17',
  'size': '4661443 KB'},
 {'url': 'https://geo.fbds.org.br/PI/',
  'type': 'folder',
  'name': 'PI',
  'date': '2021-08-06 02:25',
  'size': '7038083 KB'},
 {'url': 'https://geo.fbds.org.br/PR/',
  'type': 'folder',
  'name': 'PR',
  'date': '2019-07-29 15:40',
  'size': '15859333 KB'},
 {'url': 'https://geo.fbds.org.br/RJ/',
  'type': 'folder',
  'name': 'RJ',
  'date': '2019-07-29 15:40',
  'size': '2922197 KB'},
 {'url': 'https://geo.fbds.org.br/RN/',
  'type': 'folder',
  'name': 'RN',
  'date': '2021-10-15 03:30',
  'size': '3604598 KB'},
 {'url': 'https://geo.fbds.org.br/RO/',
  'type': 'folder',
  'name': 'RO',
  'date': '2022-10-10 20:44',
  'size': '3439089 KB'},
 {'url': 'https://geo.fbds.org.br/RR/',
  'type': 'folder',
  'name': 'RR',
  'date': '2021-08-06 03:30',
  'size': '2331837 KB'},
 {'url': 'https://geo.fbds.org.br/RS/',
  'type': 'folder',
  'name': 'RS',
  'date': '2018-02-01 08:55',
  'size': '11737180 KB'},
 {'url': 'https://geo.fbds.org.br/SC/',
  'type': 'folder',
  'name': 'SC',
  'date': '2018-02-01 17:51',
  'size': '14638911 KB'},
 {'url': 'https://geo.fbds.org.br/SE/',
  'type': 'folder',
  'name': 'SE',
  'date': '2022-04-30 01:24',
  'size': '1492475 KB'},
 {'url': 'https://geo.fbds.org.br/SP/',
  'type': 'folder',
  'name': 'SP',
  'date': '2024-08-14 12:34',
  'size': '26787993 KB'},
 {'url': 'https://geo.fbds.org.br/TO/',
  'type': 'folder',
  'name': 'TO',
  'date': '2021-10-04 14:52',
  'size': '10459885 KB'}]

In [24]:
estado = fbds.get_state(uf='SP')
estado

2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/

{'url': 'https://geo.fbds.org.br/SP/',
 'type': 'folder',
 'name': 'SP',
 'date': '2024-08-14 12:34',
 'size': '26787993 KB'}

In [25]:
fbds.states

2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/

['AC',
 'AL',
 'AM',
 'AP',
 'BA',
 'CE',
 'DF',
 'ES',
 'GO',
 'MA',
 'MG',
 'MS',
 'MT',
 'PA',
 'PB',
 'PE',
 'PI',
 'PR',
 'RJ',
 'RN',
 'RO',
 'RR',
 'RS',
 'SC',
 'SE',
 'SP',
 'TO']

In [26]:
pd.DataFrame(estados).head()

                           url    type name              date         size
0  https://geo.fbds.org.br/AC/  folder   AC  2022-10-10 14:32   1339563 KB
1  https://geo.fbds.org.br/AL/  folder   AL  2022-04-30 01:22   1789015 KB
2  https://geo.fbds.org.br/AM/  folder   AM  2022-10-10 14:42  12583137 KB
3  https://geo.fbds.org.br/AP/  folder   AP  2022-10-10 14:56   1557080 KB
4  https://geo.fbds.org.br/BA/  folder   BA  2022-12-08 20:19  15946035 KB

Obtem um estado específico

In [27]:
state = fbds.get_state(uf='SP')
state

2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/

{'url': 'https://geo.fbds.org.br/SP/',
 'type': 'folder',
 'name': 'SP',
 'date': '2024-08-14 12:34',
 'size': '26787993 KB'}

<br>

---

### Municipios

Lista municípios de um estado.

In [28]:
municipios = fbds.get_municipalities(uf='SP')
municipios[0:3]

2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:52 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:52 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/

[{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/',
  'type': 'folder',
  'name': 'ADAMANTINA',
  'date': '2018-02-01 18:45',
  'size': '26045 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADOLFO/',
  'type': 'folder',
  'name': 'ADOLFO',
  'date': '2024-08-14 11:29',
  'size': '19110 KB'},
 {'url': 'https://geo.fbds.org.br/SP/AGUAI/',
  'type': 'folder',
  'name': 'AGUAI',
  'date': '2024-08-14 11:32',
  'size': '48900 KB'}]

In [29]:
df = pd.DataFrame(municipios)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 646 entries, 0 to 645
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   url     646 non-null    object
 1   type    646 non-null    object
 2   name    646 non-null    object
 3   date    646 non-null    object
 4   size    646 non-null    object
dtypes: object(5)
memory usage: 25.4+ KB

,url,type,name,date,size
0,https://geo.fbds.org.br/SP/ADAMANTINA/,folder,ADAMANTINA,2018-02-01 18:45,26045 KB
1,https://geo.fbds.org.br/SP/ADOLFO/,folder,ADOLFO,2024-08-14 11:29,19110 KB
2,https://geo.fbds.org.br/SP/AGUAI/,folder,AGUAI,2024-08-14 11:32,48900 KB
3,https://geo.fbds.org.br/SP/AGUAS_DA_PRATA/,folder,AGUAS_DA_PRATA,2018-02-01 18:48,42071 KB
4,https://geo.fbds.org.br/SP/AGUAS_DE_LINDOIA/,folder,AGUAS_DE_LINDOIA,2018-02-01 18:49,35362 KB

In [30]:
fbds.municipios(uf='SP')

2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/

['ADAMANTINA',
 'ADOLFO',
 'AGUAI',
 'AGUAS_DA_PRATA',
 'AGUAS_DE_LINDOIA',
 'AGUAS_DE_SANTA_BARBARA',
 'AGUAS_DE_SAO_PEDRO',
 'AGUDOS',
 'ALAMBARI',
 'ALFREDO_MARCONDES',
 'ALTAIR',
 'ALTINOPOLIS',
 'ALTO_ALEGRE',
 'ALUMINIO',
 'ALVARES_FLORENCE',
 'ALVARES_MACHADO',
 'ALVARO_DE_CARVALHO',
 'ALVINLANDIA',
 'AMERICANA',
 'AMERICO_BRASILIENSE',
 'AMERICO_DE_CAMPOS',
 'AMPARO',
 'ANALANDIA',
 'ANDRADINA',
 'ANGATUBA',
 'ANHEMBI',
 'ANHUMAS',
 'APARECIDA',
 'APARECIDA_DOESTE',
 'APIAI',
 'ARACARIGUAMA',
 'ARACATUBA',
 'ARACOIABA_DA_SERRA',
 'ARAMINA',
 'ARANDU',
 'ARAPEI',
 'ARARAQUARA',
 'ARARAS',
 'ARCO_IRIS',
 'AREALVA',
 'AREIAS',
 'AREIOPOLIS',
 'ARIRANHA',
 'ARTUR_NOGUEIRA',
 'ARUJA',
 'ASPASIA',
 'ASSIS',
 'ATIBAIA',
 'AURIFLAMA',
 'AVAI',
 'AVANHANDAVA',
 'AVARE',
 'BADY_BASSITT',
 'BALBINOS',
 'BALSAMO',
 'BANANAL',
 'BARAO_DE_ANTONINA',
 'BARBOSA',
 'BARIRI',
 'BARRA _DO_TURVO',
 'BARRA_BONITA',
 'BARRA_DO_CHAPEU',
 'BARRA_DO_TURVO',
 'BARRETOS',
 'BARRINHA',
 'BARUERI',
 'BASTOS',
 'BATATAIS',
 'BAURU',
 'BEBEDOURO',
 'BENTO_DE_ABREU',
 'BERNARDINO_DE_CAMPOS',
 'BERTIOGA',
 'BILAC',
 'BIRIGUI',
 'BIRITIBA_MIRIM',
 'BOA_ESPERANCA_DO_SUL',
 'BOCAINA',
 'BOFETE',
 'BOITUVA',
 'BOM_JESUS_DOS_PERDOES',
 'BOM_SUCESSO_DE_ITARARE',
 'BORA',
 'BORACEIA',
 'BORBOREMA',
 'BOREBI',
 'BOTUCATU',
 'BRAGANCA_PAULISTA',
 'BRAUNA',
 'BREJO_ALEGRE',
 'BRODOWSKI',
 'BROTAS',
 'BURI',
 'BURITAMA',
 'BURITIZAL',
 'CABRALIA_PAULISTA',
 'CABREUVA',
 'CACAPAVA',
 'CACHOEIRA_PAULISTA',
 'CACONDE',
 'CAFELANDIA',
 'CAIABU',
 'CAIEIRAS',
 'CAIUA',
 'CAJAMAR',
 'CAJATI',
 'CAJOBI',
 'CAJURU',
 'CAMPINA_DO_MONTE_ALEGRE',
 'CAMPINAS',
 'CAMPO_LIMPO_PAULISTA',
 'CAMPOS_DO_JORDAO',
 'CAMPOS_NOVOS_PAULISTA',
 'CANANEIA',
 'CANAS',
 'CANDIDO_MOTA',
 'CANDIDO_RODRIGUES',
 'CANITAR',
 'CAPAO_BONITO',
 'CAPELA_DO_ALTO',
 'CAPIVARI',
 'CARAGUATATUBA',
 'CARAPICUIBA',
 'CARDOSO',
 'CASA_BRANCA',
 'CASSIA_DOS_COQUEIROS',
 'CASTILHO',
 'CATANDUVA',
 'CATIGUA',
 'CEDRAL',
 'CERQUEIRA_CESAR',
 'CERQUILHO',
 'CESARIO_LANGE',
 'CHARQUEADA',
 'CHAVANTES',
 'CLEMENTINA',
 'COLINA',
 'COLOMBIA',
 'CONCHAL',
 'CONCHAS',
 'CORDEIROPOLIS',
 'COROADOS',
 'CORONEL_MACEDO',
 'CORUMBATAI',
 'COSMOPOLIS',
 'COSMORAMA',
 'COTIA',
 'CRAVINHOS',
 'CRISTAIS_PAULISTA',
 'CRUZALIA',
 'CRUZEIRO',
 'CUBATAO',
 'CUNHA',
 'DESCALVADO',
 'DIADEMA',
 'DIRCE_REIS',
 'DIVINOLANDIA',
 'DOBRADA',
 'DOIS_CORREGOS',
 'DOLCINOPOLIS',
 'DOURADO',
 'DRACENA',
 'DUARTINA',
 'DUMONT',
 'ECHAPORA',
 'ELDORADO',
 'ELIAS_FAUSTO',
 'ELISIARIO',
 'EMBAUBA',
 'EMBU_DAS_ARTES',
 'EMBU_GUACU',
 'EMILIANOPOLIS',
 'ENGENHEIRO_COELHO',
 'ESPIRITO_SANTO_DO_PINHAL',
 'ESPIRITO_SANTO_DO_TURVO',
 'ESTIVA_GERBI',
 'ESTRELA_DO_NORTE',
 'ESTRELA_DOESTE',
 'EUCLIDES_DA_CUNHA_PAULISTA',
 'FARTURA',
 'FERNANDO_PRESTES',
 'FERNANDOPOLIS',
 'FERNAO',
 'FERRAZ_DE_VASCONCELOS',
 'FLORA_RICA',
 'FLOREAL',
 'FLORIDA_PAULISTA',
 'FLORINIA',
 'FRANCA',
 'FRANCISCO_MORATO',
 'FRANCO_DA_ROCHA',
 'GABRIEL_MONTEIRO',
 'GALIA',
 'GARCA',
 'GASTAO_VIDIGAL',
 'GAVIAO_PEIXOTO',
 'GENERAL_SALGADO',
 'GETULINA',
 'GLICERIO',
 'GUAICARA',
 'GUAIMBE',
 'GUAIRA',
 'GUAPIACU',
 'GUAPIARA',
 'GUARA',
 'GUARACAI',
 'GUARACI',
 'GUARANI_DOESTE',
 'GUARANTA',
 'GUARARAPES',
 'GUARAREMA',
 'GUARATINGUETA',
 'GUAREI',
 'GUARIBA',
 'GUARUJA',
 'GUARULHOS',
 'GUATAPARA',
 'GUZOLANDIA',
 'HERCULANDIA',
 'HOLAMBRA',
 'HORTOLANDIA',
 'IACANGA',
 'IACRI',
 'IARAS',
 'IBATE',
 'IBIRA',
 'IBIRAREMA',
 'IBITINGA',
 'IBIUNA',
 'ICEM',
 'IEPE',
 'IGARACU_DO_TIETE',
 'IGARAPAVA',
 'IGARATA',
 'IGUAPE',
 'ILHA_COMPRIDA',
 'ILHA_SOLTEIRA',
 'ILHABELA',
 'INDAIATUBA',
 'INDIANA',
 'INDIAPORA',
 'INUBIA_PAULISTA',
 'IPAUSSU',
 'IPERO',
 'IPEUNA',
 'IPIGUA',
 'IPORANGA',
 'IPUA',
 'IRACEMAPOLIS',
 'IRAPUA',
 'IRAPURU',
 'ITABERA',
 'ITAI',
 'ITAJOBI',
 'ITAJU',
 'ITANHAEM',
 'ITAOCA',
 'ITAPECERICA_DA_SERRA',
 'ITAPETININGA',
 'ITAPEVA',
 'ITAPEVI',
 'ITAPIRA',
 'ITAPIRAPUA_PAULISTA',
 'ITAPOLIS',
 'ITAPORANGA',
 'ITAPUI',
 'ITAPURA',
 'ITAQUAQUECETUBA',
 'ITARARE',
 'ITARIRI',
 'ITATIBA',
 'ITATINGA',
 'ITIRAPINA',
 'ITIRAPUA',
 'ITOBI',
 'ITU',
 'ITUPEVA',
 'ITUVERAVA',
 'JABORANDI',
 'JABOTICABAL',
 'JACAREI',
 'JACI',
 'JACUPIRANGA',
 'JAGUARIUNA',
 'JALES',
 'JAMBEIRO',
 'JANDIRA',
 'JARDINOPOLIS',
 'JARINU',
 'JAU',
 'JERIQUARA',
 'JOANOPOLIS',
 'JOAO_RAMALHO',
 'JOSE_BONIFACIO',
 'JULIO_MESQUITA',
 'JUMIRIM',
 'JUNDIAI',
 'JUNQUEIROPOLIS',
 'JUQUIA',
 'JUQUITIBA',
 'LAGOINHA',
 'LARANJAL_PAULISTA',
 'LAVINIA',
 'LAVRINHAS',
 'LEME',
 'LENCOIS_PAULISTA',
 'LIMEIRA',
 'LINDOIA',
 'LINS',
 'LORENA',
 'LOURDES',
 'LOUVEIRA',
 'LUCELIA',
 'LUCIANOPOLIS',
 'LUIS_ANTONIO',
 'LUIZIANIA',
 'LUPERCIO',
 'LUTECIA',
 'MACATUBA',
 'MACAUBAL',
 'MACEDONIA',
 'MAGDA',
 'MAIRINQUE',
 'MAIRIPORA',
 'MANDURI',
 'MARABA_PAULISTA',
 'MARACAI',
 'MARAPOAMA',
 'MARIAPOLIS',
 'MARILIA',
 'MARINOPOLIS',
 'MARTINOPOLIS',
 'MATAO',
 'MAUA',
 'MENDONCA',
 'MERIDIANO',
 'MESOPOLIS',
 'MIGUELOPOLIS',
 'MINEIROS_DO_TIETE',
 'MIRA_ESTRELA',
 'MIRACATU',
 'MIRANDOPOLIS',
 'MIRANTE_DO_PARANAPANEMA',
 'MIRASSOL',
 'MIRASSOLANDIA',
 'MOCOCA',
 'MOGI_DAS_CRUZES',
 'MOGI_GUACU',
 'MOGI_MIRIM',
 'MOMBUCA',
 'MONCOES',
 'MONGAGUA',
 'MONTE_ALEGRE_DO_SUL',
 'MONTE_ALTO',
 'MONTE_APRAZIVEL',
 'MONTE_AZUL_PAULISTA',
 'MONTE_CASTELO',
 'MONTE_MOR',
 'MONTEIRO_LOBATO',
 'MORRO_AGUDO',
 'MORUNGABA',
 'MOTUCA',
 'MURUTINGA_DO_SUL',
 'NANTES',
 'NARANDIBA',
 'NATIVIDADE_DA_SERRA',
 'NAZARE_PAULISTA',
 'NEVES_PAULISTA',
 'NHANDEARA',
 'NIPOA',
 'NOVA_ALIANCA',
 'NOVA_CAMPINA',
 'NOVA_CANAA_PAULISTA',
 'NOVA_CASTILHO',
 'NOVA_EUROPA',
 'NOVA_GRANADA',
 'NOVA_GUATAPORANGA',
 'NOVA_INDEPENDENCIA',
 'NOVA_LUZITANIA',
 'NOVA_ODESSA',
 'NOVAIS',
 'NOVO_HORIZONTE',
 'NUPORANGA',
 'OCAUCU',
 'OLEO',
 'OLIMPIA',
 'ONDA_VERDE',
 'ORIENTE',
 'ORINDIUVA',
 'ORLANDIA',
 'OSASCO',
 'OSCAR_BRESSANE',
 'OSVALDO_CRUZ',
 'OURINHOS',
 'OURO_VERDE',
 'OUROESTE',
 'PACAEMBU',
 'PALESTINA',
 'PALMARES_PAULISTA',
 'PALMEIRA_DOESTE',
 'PALMITAL',
 'PANORAMA',
 'PARAGUACU_PAULISTA',
 'PARAIBUNA',
 'PARAISO',
 'PARANAPANEMA',
 'PARANAPUA',
 'PARAPUA',
 'PARDINHO',
 'PARIQUERA_ACU',
 'PARISI',
 'PATROCINIO_PAULISTA',
 'PAULICEIA',
 'PAULINIA',
 'PAULISTANIA',
 'PAULO_DE_FARIA',
 'PEDERNEIRAS',
 'PEDRA_BELA',
 'PEDRANOPOLIS',
 'PEDREGULHO',
 'PEDREIRA',
 'PEDRINHAS_PAULISTA',
 'PEDRO_DE_TOLEDO',
 'PENAPOLIS',
 'PEREIRA_BARRETO',
 'PEREIRAS',
 'PERUIBE',
 'PIACATU',
 'PIEDADE',
 'PILAR_DO_SUL',
 'PINDAMONHANGABA',
 'PINDORAMA',
 'PINHALZINHO',
 'PIQUEROBI',
 'PIQUETE',
 'PIRACAIA',
 'PIRACICABA',
 'PIRAJU',
 'PIRAJUI',
 'PIRANGI',
 'PIRAPORA_DO_BOM_JESUS',
 'PIRAPOZINHO',
 'PIRASSUNUNGA',
 'PIRATININGA',
 'PITANGUEIRAS',
 'PLANALTO',
 'PLATINA',
 'POA',
 'POLONI',
 'POMPEIA',
 'PONGAI',
 'PONTAL',
 'PONTALINDA',
 'PONTES_GESTAL',
 'POPULINA',
 'PORANGABA',
 'PORTO_FELIZ',
 'PORTO_FERREIRA',
 'POTIM',
 'POTIRENDABA',
 'PRACINHA',
 'PRADOPOLIS',
 'PRAIA_GRANDE',
 'PRATANIA',
 'PRESIDENTE_ALVES',
 'PRESIDENTE_BERNARDES',
 'PRESIDENTE_EPITACIO',
 'PRESIDENTE_PRUDENTE',
 'PRESIDENTE_VENCESLAU',
 'PROMISSAO',
 'QUADRA',
 'QUATA',
 'QUEIROZ',
 'QUELUZ',
 'QUINTANA',
 'RAFARD',
 'RANCHARIA',
 'REDENCAO_DA_SERRA',
 'REGENTE_FEIJO',
 'REGINOPOLIS',
 'REGISTRO',
 'RESTINGA',
 'RIBEIRA',
 'RIBEIRAO_BONITO',
 'RIBEIRAO_BRANCO',
 'RIBEIRAO_CORRENTE',
 'RIBEIRAO_DO_SUL',
 'RIBEIRAO_DOS_INDIOS',
 'RIBEIRAO_GRANDE',
 'RIBEIRAO_PIRES',
 'RIBEIRAO_PRETO',
 'RIFAINA',
 'RINCAO',
 'RINOPOLIS',
 'RIO_CLARO',
 'RIO_DAS_PEDRAS',
 'RIO_GRANDE_DA_SERRA',
 'RIOLANDIA',
 'RIVERSUL',
 'ROSANA',
 'ROSEIRA',
 'RUBIACEA',
 'RUBINEIA',
 'SABINO',
 'SAGRES',
 'SALES',
 'SALES_OLIVEIRA',
 'SALESOPOLIS',
 'SALMOURAO',
 'SALTINHO',
 'SALTO',
 'SALTO_DE_PIRAPORA',
 'SALTO_GRANDE',
 'SANDOVALINA',
 'SANTA_ADELIA',
 'SANTA_ALBERTINA',
 'SANTA_BARBARA_DOESTE',
 'SANTA_BRANCA',
 'SANTA_CLARA_DOESTE',
 'SANTA_CRUZ_DA_CONCEICAO',
 'SANTA_CRUZ_DA_ESPERANCA',
 'SANTA_CRUZ_DAS_PALMEIRAS',
 'SANTA_CRUZ_DO_RIO_PARDO',
 'SANTA_ERNESTINA',
 'SANTA_FE_DO_SUL',
 'SANTA_GERTRUDES',
 'SANTA_ISABEL',
 'SANTA_LUCIA',
 'SANTA_MARIA_DA_SERRA',
 'SANTA_MERCEDES',
 'SANTA_RITA_DO_PASSA_QUATRO',
 'SANTA_RITA_DOESTE',
 'SANTA_ROSA_DE_VITERBO',
 'SANTA_SALETE',
 'SANTANA_DA_PONTE_PENSA',
 'SANTANA_DE_PARNAIBA',
 'SANTO_ANASTACIO',
 'SANTO_ANDRE',
 'SANTO_ANTONIO_DA_ALEGRIA',
 'SANTO_ANTONIO_DE_POSSE',
 'SANTO_ANTONIO_DO_ARACANGUA',
 'SANTO_ANTONIO_DO_JARDIM',
 'SANTO_ANTONIO_DO_PINHAL',
 'SANTO_EXPEDITO',
 'SANTOPOLIS_DO_AGUAPEI',
 'SANTOS',
 'SAO_BENTO_DO_SAPUCAI',
 'SAO_BERNARDO_DO_CAMPO',
 'SAO_CAETANO_DO_SUL',
 'SAO_CARLOS',
 'SAO_FRANCISCO',
 'SAO_JOAO_DA_BOA_VISTA',
 'SAO_JOAO_DAS_DUAS_PONTES',
 'SAO_JOAO_DE_IRACEMA',
 'SAO_JOAO_DO_PAU_DALHO',
 'SAO_JOAQUIM_DA_BARRA',
 'SAO_JOSE_DA_BELA_VISTA',
 'SAO_JOSE_DO_BARREIRO',
 'SAO_JOSE_DO_RIO_PARDO',
 'SAO_JOSE_DO_RIO_PRETO',
 'SAO_JOSE_DOS_CAMPOS',
 'SAO_LOURENCO_DA_SERRA',
 'SAO_LUIS_DO_PARAITINGA',
 'SAO_MANUEL',
 'SAO_MIGUEL_ARCANJO',
 'SAO_PAULO',
 'SAO_PEDRO',
 'SAO_PEDRO_DO_TURVO',
 'SAO_ROQUE',
 'SAO_SEBASTIAO',
 'SAO_SEBASTIAO_DA_GRAMA',
 'SAO_SIMAO',
 'SAO_VICENTE',
 'SARAPUI',
 'SARUTAIA',
 'SEBASTIANOPOLIS_DO_SUL',
 'SERRA_AZUL',
 'SERRA_NEGRA',
 'SERRANA',
 'SERTAOZINHO',
 'SETE_BARRAS',
 'SEVERINIA',
 'SILVEIRAS',
 'SOCORRO',
 'SOROCABA',
 'SUD_MENNUCCI',
 'SUMARE',
 'SUZANAPOLIS',
 'SUZANO',
 'TABAPUA',
 'TABATINGA',
 'TABOAO_DA_SERRA',
 'TACIBA',
 'TAGUAI',
 'TAIACU',
 'TAIUVA',
 'TAMBAU',
 'TANABI',
 'TAPIRAI',
 'TAPIRATIBA',
 'TAQUARAL',
 'TAQUARITINGA',
 'TAQUARITUBA',
 'TAQUARIVAI',
 'TARABAI',
 'TARUMA',
 'TATUI',
 'TAUBATE',
 'TEJUPA',
 'TEODORO_SAMPAIO',
 'TERRA_ROXA',
 'TIETE',
 'TIMBURI',
 'TORRE_DE_PEDRA',
 'TORRINHA',
 'TRABIJU',
 'TREMEMBE',
 'TRES_FRONTEIRAS',
 'TUIUTI',
 'TUPA',
 'TUPI_PAULISTA',
 'TURIUBA',
 'TURMALINA',
 'UBARANA',
 'UBATUBA',
 'UBIRAJARA',
 'UCHOA',
 'UNIAO_PAULISTA',
 'URANIA',
 'URU',
 'URUPES',
 'VALENTIM_GENTIL',
 'VALINHOS',
 'VALPARAISO',
 'VARGEM',
 'VARGEM_GRANDE_DO_SUL',
 'VARGEM_GRANDE_PAULISTA',
 'VARZEA_PAULISTA',
 'VERA_CRUZ',
 'VINHEDO',
 'VIRADOURO',
 'VISTA_ALEGRE_DO_ALTO',
 'VITORIA_BRASIL',
 'VOTORANTIM',
 'VOTUPORANGA',
 'ZACARIAS']

Obtem um município específico.

In [31]:
municipio = fbds.get_municipalitie(
    uf="SP",
    municipality="SANTOS",
)
municipio

2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/

{'url': 'https://geo.fbds.org.br/SP/SANTOS/',
 'type': 'folder',
 'name': 'SANTOS',
 'date': '2026-09-11 23:39',
 'size': '28872 KB'}

<br>

---

### Layers

Lista _layers_ de um município.

In [32]:
layers = fbds.get_layers(
    municipality="ADAMANTINA",
    uf="SP",
)
layers[:3]

2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/ADAMANTINA/

[{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/APP/',
  'type': 'folder',
  'name': 'APP',
  'date': '2026-09-11 23:39',
  'size': '4874 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/',
  'type': 'folder',
  'name': 'HIDROGRAFIA',
  'date': '2018-02-01 18:45',
  'size': '4244 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/MAPAS/',
  'type': 'folder',
  'name': 'MAPAS',
  'date': '2026-09-11 23:39',
  'size': '14364 KB'}]

Obtem layers de um município específico.

In [33]:
layer = fbds.get_layer(
    municipality="ADAMANTINA",
    uf="SP",
    layer="APP",
)
layer

2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/ADAMANTINA/

{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/APP/',
 'type': 'folder',
 'name': 'APP',
 'date': '2026-09-11 23:39',
 'size': '4874 KB'}

In [34]:
layer = fbds.get_layer(
    municipality="ADAMANTINA",
    uf="SP",
    layer="HIDROGRAFIA",
)
layer

2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:53 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/
2026-09-25 01:09:54 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:54 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:54 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:54 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:54 - FBDS - INFO - Obtendo estados
2026-09-25 01:09:54 - FBDS - INFO - [Cache] https://geo.fbds.org.br/
2026-09-25 01:09:54 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/
2026-09-25 01:09:54 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/ADAMANTINA/

{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/',
 'type': 'folder',
 'name': 'HIDROGRAFIA',
 'date': '2018-02-01 18:45',
 'size': '4244 KB'}

<br>

---

## _Download_

In [35]:
# Lista de arquivos para download (do exemplo)
files_to_download = fbds.get_links(
    url=layer["url"],
    ignore_first=2,
)
files_to_download[0:3]

2026-09-25 01:09:54 - FBDS - INFO - [Cache] https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/

[{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/SP_3500105_MASSAS_DAGUA.cpg',
  'type': 'file',
  'name': 'SP_3500105_MASSAS_DAGUA.cpg',
  'date': '2023-08-24 02:27',
  'size': '0 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/SP_3500105_MASSAS_DAGUA.dbf',
  'type': 'file',
  'name': 'SP_3500105_MASSAS_DAGUA.dbf',
  'date': '2023-08-24 02:27',
  'size': '15 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/SP_3500105_MASSAS_DAGUA.prj',
  'type': 'file',
  'name': 'SP_3500105_MASSAS_DAGUA.prj',
  'date': '2021-08-14 23:37',
  'size': '0 KB'}]

<br>

---

### ThreadPoolExecutor

Download usando threads (melhor para downloads)

In [36]:
# 1. Marca o tempo inicial
inicio = time.perf_counter()

# Função
results = fbds.download_files_parallel(
    url_list=files_to_download,
    max_concurrent=4,
)

# 2. Marca o tempo final
fim = time.perf_counter()

# 3. Calcula a diferença
tempo_total = fim - inicio

print(f"Tempo de execução: {tempo_total:.4f} segundos")

2026-09-25 01:09:54 - FBDS - INFO - Iniciando nova sessão de download
2026-09-25 01:09:54 - FBDS - ERROR - Erro durante o download: FBDS.download_files_async() got an unexpected keyword argument 'output_path'

Tempo de execução: 0.0030 segundos

<br>

---

### Async

Iniciando _download_ assíncrono...

In [37]:
# 1. Marca o tempo inicial
inicio = time.perf_counter()

# Função
results = await fbds.download_files_async(
    url_list=files_to_download,
    max_concurrent=5,  # Número de downloads simultâneos
)

# 2. Marca o tempo final
fim = time.perf_counter()

# 3. Calcula a diferença
tempo_total = fim - inicio

print(f"Tempo de execução: {tempo_total:.4f} segundos")

Downloading files: 100%|##########| 24/24 [00:02<00:00, 10.04it/s]

Tempo de execução: 2.3971 segundos

<br>

---

### Resultados

In [38]:
# Mostra resultados
print("Resultados:")
successes = [r for r in results if r["status"] == "sucesso"]
errors = [r for r in results if r["status"] == "erro"]
cached = [r for r in results if r.get("cached", False)]

print(f"Downloads com sucesso: {len(successes)} de {len(results)}")
print(f"Erros: {len(errors)} de {len(results)}")
print(f"Arquivos do cache: {len(cached)} de {len(results)}")

# Mostra erros se houver
if errors:
    print("Erros encontrados:")
    for error in errors:
        print(f"- {error['nome']}: {error['erro']}")

Resultados:
Downloads com sucesso: 24 de 24
Erros: 0 de 24
Arquivos do cache: 0 de 24