<br>

# FDBS

Script para obter dados usando LXML.

Quero simplificar!

<br>

Michel Metran\
Data: 02.11.2025\
Atualizado em: 02.11.2025

In [46]:
from pathlib import Path

import pandas as pd

import pyFDBS

<br>

---

## FBDS

Instancia a classe

In [47]:
fdbs = pyFDBS.FBDS()

<br>

---

### States

Lista estados

In [48]:
states = fdbs.get_states()
states[0:3]

[{'url': 'https://geo.fbds.org.br/AC/',
  'type': 'folder',
  'name': 'AC',
  'date': '2022-10-10 14:32',
  'size': '1339818 KB'},
 {'url': 'https://geo.fbds.org.br/AL/',
  'type': 'folder',
  'name': 'AL',
  'date': '2022-04-30 01:22',
  'size': '1792907 KB'},
 {'url': 'https://geo.fbds.org.br/AM/',
  'type': 'folder',
  'name': 'AM',
  'date': '2022-10-10 14:42',
  'size': '12584553 KB'}]

In [49]:
pd.DataFrame(states).head()

                           url    type name              date         size
0  https://geo.fbds.org.br/AC/  folder   AC  2022-10-10 14:32   1339818 KB
1  https://geo.fbds.org.br/AL/  folder   AL  2022-04-30 01:22   1792907 KB
2  https://geo.fbds.org.br/AM/  folder   AM  2022-10-10 14:42  12584553 KB
3  https://geo.fbds.org.br/AP/  folder   AP  2022-10-10 14:56   1557267 KB
4  https://geo.fbds.org.br/BA/  folder   BA  2022-12-08 20:19  15956546 KB

Obtem um estado específico

In [50]:
state = fdbs.get_state(uf='SP')
state

{'url': 'https://geo.fbds.org.br/SP/',
 'type': 'folder',
 'name': 'SP',
 'date': '2024-08-14 12:34',
 'size': '26834380 KB'}

<br>

---

### Municipios

Lista municípios de um estado.

In [51]:
municipios = fdbs.get_municipalities(uf='SP')
municipios[0:3]

[{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/',
  'type': 'folder',
  'name': 'ADAMANTINA',
  'date': '2018-02-01 18:45',
  'size': '26097 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADOLFO/',
  'type': 'folder',
  'name': 'ADOLFO',
  'date': '2024-08-14 11:29',
  'size': '19150 KB'},
 {'url': 'https://geo.fbds.org.br/SP/AGUAI/',
  'type': 'folder',
  'name': 'AGUAI',
  'date': '2024-08-14 11:32',
  'size': '48979 KB'}]

In [52]:
pd.DataFrame(municipios).head()

,url,type,name,date,size
0,https://geo.fbds.org.br/SP/ADAMANTINA/,folder,ADAMANTINA,2018-02-01 18:45,26097 KB
1,https://geo.fbds.org.br/SP/ADOLFO/,folder,ADOLFO,2024-08-14 11:29,19150 KB
2,https://geo.fbds.org.br/SP/AGUAI/,folder,AGUAI,2024-08-14 11:32,48979 KB
3,https://geo.fbds.org.br/SP/AGUAS_DA_PRATA/,folder,AGUAS_DA_PRATA,2018-02-01 18:48,42165 KB
4,https://geo.fbds.org.br/SP/AGUAS_DE_LINDOIA/,folder,AGUAS_DE_LINDOIA,2018-02-01 18:49,35406 KB

Obtem um município específico.

In [53]:
municipio = fdbs.get_municipalitie(uf='SP', municipality='SANTOS')
municipio

{'url': 'https://geo.fbds.org.br/SP/SANTOS/',
 'type': 'folder',
 'name': 'SANTOS',
 'date': '2024-08-14 12:28',
 'size': '28960 KB'}

<br>

---

### Layers

Lista layers de um município.

In [54]:
layers = fdbs.get_layers(municipality='ADAMANTINA', uf='SP')
layers[:3]

[{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/APP/',
  'type': 'folder',
  'name': 'APP',
  'date': '2021-08-06 04:25',
  'size': '4887 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/',
  'type': 'folder',
  'name': 'HIDROGRAFIA',
  'date': '2018-02-01 18:45',
  'size': '4244 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/MAPAS/',
  'type': 'folder',
  'name': 'MAPAS',
  'date': '2021-08-06 04:25',
  'size': '14394 KB'}]

Obtem layers de um município específico.

In [55]:
layer = fdbs.get_layer(municipality='ADAMANTINA', uf='SP', layer='APP')
layer

{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/APP/',
 'type': 'folder',
 'name': 'APP',
 'date': '2021-08-06 04:25',
 'size': '4887 KB'}

In [56]:
layer = fdbs.get_layer(municipality='ADAMANTINA', uf='SP', layer='HIDROGRAFIA')
layer

{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/',
 'type': 'folder',
 'name': 'HIDROGRAFIA',
 'date': '2018-02-01 18:45',
 'size': '4244 KB'}

<br>

---

## Download

In [57]:
project_path = Path('.').absolute().parents[2]
project_path

WindowsPath('d:/Codes/GitHub/Org - Open Geodata/pyFBDS')

In [58]:
# Diretório de saída
output_dir = project_path / 'data' / 'output'
output_dir.mkdir(parents=True, exist_ok=True)
output_dir

WindowsPath('d:/Codes/GitHub/Org - Open Geodata/pyFBDS/data/output')

In [59]:
# Lista de arquivos para download (do exemplo)
files_to_download = fdbs.get_links(url=layer['url'], ignore_first=2)
files_to_download[0:3]

[{'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/SP_3500105_MASSAS_DAGUA.cpg',
  'type': 'file',
  'name': 'SP_3500105_MASSAS_DAGUA.cpg',
  'date': '2023-08-24 02:27',
  'size': '0 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/SP_3500105_MASSAS_DAGUA.dbf',
  'type': 'file',
  'name': 'SP_3500105_MASSAS_DAGUA.dbf',
  'date': '2023-08-24 02:27',
  'size': '15 KB'},
 {'url': 'https://geo.fbds.org.br/SP/ADAMANTINA/HIDROGRAFIA/SP_3500105_MASSAS_DAGUA.prj',
  'type': 'file',
  'name': 'SP_3500105_MASSAS_DAGUA.prj',
  'date': '2021-08-14 23:37',
  'size': '0 KB'}]

In [60]:
# Download usando threads (melhor para downloads)
print("Iniciando download com ThreadPoolExecutor...")

results_thread = pyFDBS.download_files_parallel(
    url_list=files_to_download,
    output_dir=output_dir,
    # Número de downloads simultâneos
    max_concurrent=4,
)

2026-08-18 02:03:01 - FBDS - INFO - Iniciando nova sessão de download

Iniciando download com ThreadPoolExecutor...

Downloading files: 100%|##########| 24/24 [00:02<00:00,  8.14it/s]
2026-08-18 02:03:04 - FBDS - INFO - Iniciando nova sessão de download
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_MASSAS_DAGUA.cpg (5 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_MASSAS_DAGUA.dbf (15202 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_MASSAS_DAGUA.prj (418 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_MASSAS_DAGUA.shp (29520 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_MASSAS_DAGUA.shp.xml (28773 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_MASSAS_DAGUA.shx (420 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_NASCENTES.cpg (5 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_NASCENTES.dbf (211985 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_NASCENTES.prj (418 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_NASCENTES.shp (19168 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_NASCENTES.shp.xml (23094 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_NASCENTES.shx (5548 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_DUPLOS.cpg (5 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_DUPLOS.dbf (25822 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_DUPLOS.prj (418 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_DUPLOS.shp (283688 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_DUPLOS.shp.xml (18526 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_DUPLOS.shx (732 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_SIMPLES.cpg (5 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_SIMPLES.dbf (801154 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_SIMPLES.prj (418 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_SIMPLES.shp (2725060 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_SIMPLES.shp.xml (30514 bytes)
2026-08-18 02:03:04 - FBDS - INFO - Download concluído: SP_3500105_RIOS_SIMPLES.shx (19876 bytes)
2026-08-18 02:03:04 - FBDS - INFO - === Resumo da Sessão de Download ===
2026-08-18 02:03:04 - FBDS - INFO - Downloads com sucesso: 24 de 24
2026-08-18 02:03:04 - FBDS - INFO - Duração total: 0:00:00.035499

In [61]:
pyFDBS.download_files_parallel

In [62]:
# Download usando asyncio
print("Iniciando download assíncrono...")

try:
    results = pyFDBS.download_files_async(
        url_list=files_to_download,
        output_dir=output_dir,
        max_concurrent=5,  # Número de downloads simultâneos
    )
except:
    pass

Iniciando download assíncrono...

In [63]:
# Mostra resultados
print("Resultados:")
successes = [r for r in results_thread if r["status"] == "sucesso"]
errors = [r for r in results_thread if r["status"] == "erro"]
cached = [r for r in results_thread if r.get("cached", False)]


print(f"Downloads com sucesso: {len(successes)} de {len(results_thread)}")
print(f"Erros: {len(errors)} de {len(results_thread)}")
print(f"Arquivos do cache: {len(cached)} de {len(results_thread)}")

# Mostra erros se houver
if errors:
    print("Erros encontrados:")
    for error in errors:
        print(f"- {error['nome']}: {error['erro']}")

Resultados:
Downloads com sucesso: 24 de 24
Erros: 0 de 24
Arquivos do cache: 0 de 24